// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POC.Api.Persistence;

#nullable disable

namespace POC.Api.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("POC.Api.Persistence.Entities.CheckoutSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("CheckoutSessions");
                });

            modelBuilder.Entity("POC.Api.Persistence.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("POC.Api.Persistence.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BasketId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("POC.Api.Persistence.Entities.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("OrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("POC.Api.Persistence.Entities.Performance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PerformanceDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("POC.Api.Persistence.Entities.Price", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("POC.Api.Persistence.Entities.Seat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OrderItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PerformanceId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PriceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("PerformanceId");

                    b.HasIndex("PriceId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("POC.Api.Persistence.Entities.CheckoutSession", b =>
                {
                    b.HasOne("POC.Api.Persistence.Entities.Order", "Order")
                        .WithOne("CheckoutSession")
                        .HasForeignKey("POC.Api.Persistence.Entities.CheckoutSession", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("POC.Api.Persistence.Entities.OrderItem", b =>
                {
                    b.HasOne("POC.Api.Persistence.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("POC.Api.Persistence.Entities.Performance", b =>
                {
                    b.HasOne("POC.Api.Persistence.Entities.Event", "Event")
                        .WithMany("Performances")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("POC.Api.Persistence.Entities.Seat", b =>
                {
                    b.HasOne("POC.Api.Persistence.Entities.OrderItem", "OrderItem")
                        .WithMany("Seats")
                        .HasForeignKey("OrderItemId");

                    b.HasOne("POC.Api.Persistence.Entities.Performance", "Performance")
                        .WithMany("Seats")
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POC.Api.Persistence.Entities.Price", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderItem");

                    b.Navigation("Performance");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("POC.Api.Persistence.Entities.Event", b =>
                {
                    b.Navigation("Performances");
                });

            modelBuilder.Entity("POC.Api.Persistence.Entities.Order", b =>
                {
                    b.Navigation("CheckoutSession")
                        .IsRequired();

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("POC.Api.Persistence.Entities.OrderItem", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("POC.Api.Persistence.Entities.Performance", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
